import { SyntheticEvent } from "./event.js";

declare global {
  interface HTMLElement {
    blockId?: string;
    __handlers?: Record<string, EventHandler<any>>;
  }

  interface Node {
    blockId?: string;
    __handlers?: Record<string, EventHandler<any>>;
  }

  interface ChildNode {
    blockId?: string;
    __handlers?: Record<string, EventHandler<any>>;
  }

  interface DocumentFragment {
    blockId?: string;
    __handlers?: any;
  }
}

type EventHandler<T extends EventTarget = EventTarget> = (
  e: SyntheticEvent<T>,
) => void;

type SyntheticEventHandler<
  T extends HTMLElement,
  K extends keyof HTMLElementEventMap,
> = (e: SyntheticEvent<T>) => void;

type DOMEventProps<T extends HTMLElement> = {
  [K in keyof HTMLElementEventMap as `on${K}`]?: SyntheticEventHandler<T, K>;
};

/*
  type Attrs<T extends keyof HTMLElementTagNameMap> = Partial<
  HTMLElementTagNameMap[T]
> &
  Partial<Omit<HTMLElementTagNameMap[T], keyof HTMLElement>> &
  DOMEventProps<HTMLElementTagNameMap[T]> & {
    class?: string
    ref?: string;
    children?: HTMLElement | HTMLElement[];
  };
*/

// type ElementRef<
//   T extends keyof HTMLElementTagNameMap = keyof HTMLElementTagNameMap,
// > = {
//   el: HTMLElementTagNameMap[T] | null;
//   _tag: T | string;
// };

type ElementRef<T> = {
  el: T | null;
  _tag: string | undefined;
};

type Attrs<T extends keyof HTMLElementTagNameMap> = Partial<
  Omit<HTMLElementTagNameMap[T], keyof HTMLElement>
> &
  DOMEventProps<HTMLElementTagNameMap[T]> & {
    /** CSS classes to apply to the element */
    class?: string;
    /** Unique ref generated by useElementRef to select this element later. */
    ref?: ElementRef<HTMLElementTagNameMap[T]>;
    children?: HTMLElement | HTMLElement[];
    style?: CSSStyleDeclaration;
  };

type TagName = keyof HTMLElementTagNameMap;
type RectorElements = {
  [K in TagName]: (attributes: Attrs<K>) => HTMLElementTagNameMap[K];
};

namespace RectorJS {
  export type Component<P = {}> = (props: P) => RectorJS.Element;
  export type AsyncComponent = {
    importFn: () => Promise<{ default: RectorJS.Component }>;
    props: any;
  };
  export type Element = HTMLElement | ChildNode | DocumentFragment;
  export type DOM = {
    [K in TagName]: (attributes: Attrs<K>) => HTMLElementTagNameMap[K];
  };
  export interface LeafRoute {
    component: () => RectorJS.Element; // required — discriminant
    config?: MetaConfig;
    middleware?: (context: MiddlewareContext) => void | Promise<void>;
    loader?: () => RectorJS.Element;

    // Explicitly forbidden — assigning these is a compile error
    layout?: never;
    children?: never;
  }
  export interface LayoutRoute {
    layout: (child: () => RectorJS.Element) => RectorJS.Element; // required — discriminant
    children: {
      [path: string]: RectorJS.Route;
    }; // required when layout is present
    middleware?: (context: MiddlewareContext) => void | Promise<void>;
    loader?: () => RectorJS.Element;

    // Explicitly forbidden
    component?: never;
    config?: never;
  }
  export type Route = LeafRoute | LayoutRoute;
}

/*
  {
    layout?: (child: () => RectorJS.Element) => HTMLElement;
    children?: {
      [path: string]: RectorJS.Route;
    };
    component?: () => RectorJS.Element;
    config?: MetaConfig;
    middleware?: (context: MiddlewareContext) => void | Promise<void>;
    loader?: () => RectorJS.Element;
  };
*/

type AttrsUsage = {
  [state: string]: AttrUseObj[];
};

type StateLoopBlocks = {
  [stateName: string]: string[];
};

type StateIfBlocks = {
  [scope: string]: {
    [stateName: string]: string[];
  };
};

type RectorElementRef<T extends keyof HTMLElementTagNameMap> = {
  [refName: string]: HTMLElementTagNameMap[T];
};
// interface IfBlockConfig {
//   rawExp: RawJSXExpression;
//   trueElement?: () => HTMLElement | ChildNode;
//   falseElement?: () => HTMLElement | ChildNode;
//   placeholder?: Range;
//   cmpId?: string;
//   childBlock?: string;
// }

type StateUseObj = {
  element: HTMLElement;
  pos: number;
  eval: () => any;
  cmpId: string;
};

type AttrUseObj = {
  element: HTMLElement;
  eval: () => any;
  attribute: string;
  cmpId: string;
};

type IfBlockConfig = {
  elementRange: Range;
  cmpId: string;
  prevVal: boolean;
  childBlock: string;
} & JSXConditionObj;

interface LoopBlockConfig {
  renderElement?: (item: any, index: number) => HTMLElement;
  startRef: Comment;
  endRef: Comment;
  keyExtractor?: (item: any, index: number) => string | number;
  cmpId?: string;
  childBlocks?: Set<string>;
  data?: JSXExpressionObj;
}

type StateUsageConfig =
  | {
      type: "condition";
      config: IfBlockConfig;
    }
  | {
      type: "loop";
      config: LoopBlockConfig;
    }
  | {
      type: "child";
      config: StateUseObj;
    }
  | {
      type: "attr";
      config: AttrUseObj;
    };

type Block = {
  componentRendered: string[];
  stateUsageCleanUps: (() => void)[];
  stateUsageRefIds: number[];
  layoutId?: number;
};

type State<T> = {
  (): T;
  /** set any value of state */
  set(val: T | ((prev: T) => T)): void;
};

type List<T> = {
  (): T[];
  /** size/length of list */
  readonly size: number;
  /** set any value of list */
  set(val: T[] | ((prev: readonly T[]) => T[])): void;
  /** update list at any index */
  update(index: number, value: T): void;
  /** insert value/values to list at any index */
  insert(index: number, ...values: T[]): void;
  /** insert value/values to list after last index */
  push(...values: T[]): void;
  /** insert value/values to list at start of list */
  unshift(...values: T[]): void;
  /** remove last item of list */
  pop(): void;
  /** remove first item of list */
  shift(): void;
  /** remove item of list at any index */
  remove(index: number): void;
  /** remove range of items from list between any indexes */
  removeRange(start: number, end: number): void;
};

// type BatchTypes = "insert" | "update" | "remove" | "removeRange";

// type RenderBatch =
//   | {
//       type: "set";
//       index?: number;
//       value?: any;
//       state: State<any> | List<any>;
//     }
//   | {
//       type: BatchTypes;
//       index?: number;
//       value?: any;
//       state: List<any>;
//     };

type RenderBatch =
  | {
      type: "set";
      oldValue: any;
      state: State<any> | List<any>;
    }
  | {
      type: "insert";
      index: number;
      values: any[];
      state: List<any>;
    }
  | {
      type: "update";
      index: number;
      value: any;
      state: List<any>;
    }
  | {
      type: "removeRange";
      start: number;
      end: number;
      state: List<any>;
    }
  | {
      type: "remove";
      index: number;
      state: List<any>;
    };

interface EffectConfig {
  [id: string]: {
    depends: State<any>[];
    scope: string;
    fn: () => void | Promise<void> | (() => void);
    cleanUp?: () => void;
    phase?: "l";
  };
}

type EffectOptions = {
  runOnMount: boolean;
  phase: "layout" | "effect";
};

type ElementInterceptors = {
  [Tag in keyof HTMLElementTagNameMap]?: (
    el: HTMLElementTagNameMap[Tag],
  ) => void;
};

// type Rector.JSX.Element = () => HTMLElement | ChildNode;

type RouteConfig = {
  middleware?: (context: MiddlewareContext) => void | Promise<void>;
  loader?: () => RectorJS.Element;
  layout?: (child: () => RectorJS.Element) => RectorJS.Element;
  children: {
    [path: string]: RectorJS.Route;
  };
};

type MetaConfig = {
  meta?: { description?: string };
  documentTitle?: string;
};

type MiddlewareContext = {
  path: string; // current path
  redirect(to: string): void;
  abort(fallbackUrl?: string): void;
};

type NavigationAction =
  | { type: "goAhead" }
  | { type: "abort"; fallbackUrl?: string }
  | { type: "redirect"; to: string };

type Route = {
  lid?: number | number[];
  component: () => RectorJS.Element;
  config?: MetaConfig;
  middleware?: (context: MiddlewareContext) => void | Promise<void>;
  loader?: () => RectorJS.Element;
};

type RootLayoutConfig = {
  middleware?: (context: MiddlewareContext) => void | Promise<void>;
  loader?: () => RectorJS.Element;
  layout?: (child: () => RectorJS.Element) => RectorJS.Element;
};
interface JSXExpressionObj {
  eval: () => any;
  states: State<any>[];
}

interface JSXConditionObj {
  eval: () => boolean;
  states: State<any>[];
  then: () => HTMLElement | ChildNode | DocumentFragment;
  else: () => HTMLElement | ChildNode | DocumentFragment;
}

const LIST_MARKER = Symbol("RECTOR_LIST");

type ListMarker<T> = { readonly [LIST_MARKER]: true; readonly value: T[] };

type GlobalStates<T> = {
  [K in keyof T]: T[K] extends ListMarker<infer U>
    ? List<U> // If it is already a List, return List Type
    : State<T[K]>; // If it is a primitive (number/string), wrap in State Type
};
// type RectorRefs = {
//   [K in keyof HTMLElementTagNameMap]: {
//     [refName: string]: HTMLElementTagNameMap[K];
//   };
// };
type ParentScope = {
  state: { [stateName: string]: State<any> };
  list: { [stateName: string]: List<any> };
};

export {
  ListMarker,
  LIST_MARKER,
  GlobalStates,
  Attrs,
  EffectConfig,
  RectorElements,
  StateIfBlocks,
  StateLoopBlocks,
  StateUseObj,
  RectorElementRef,
  IfBlockConfig,
  LoopBlockConfig,
  ElementInterceptors,
  Route,
  RouteConfig,
  JSXExpressionObj,
  JSXConditionObj,
  MetaConfig,
  RectorJS,
  AttrsUsage,
  State,
  List,
  RenderBatch,
  StateUsageConfig,
  Block,
  NavigationAction,
  EffectOptions,
  ElementRef,
  ParentScope,
  RootLayoutConfig,
};

// in future

// interface GlobalAttributes {
//   id?: string;
//   class?: string;
//   style?: string;
//   title?: string;
//   hidden?: boolean;
//   children?: HTMLElement | HTMLElement[];
//   [key: string]: any; // allow data-*, aria-*
// }

// interface ElementAttributesMap {
//   div: GlobalAttributes & {
//     // no innerHTML, innerText
//   };
//   input: GlobalAttributes & {
//     type?: string;
//     name?: string;
//     value?: string;
//     placeholder?: string;
//     disabled?: boolean;
//   };
//   // Add more as needed
// }

// type Attrs<T extends keyof ElementAttributesMap> = ElementAttributesMap[T];
