import { SyntheticEvent } from "./event.js";

declare global {
  interface HTMLElement {
    blockId?: string;
    __handlers?: Record<string, EventHandler<any>>;
  }

  interface Node {
    blockId?: string;
    __handlers?: Record<string, EventHandler<any>>;
  }

  interface ChildNode {
    blockId?: string;
    __handlers?: Record<string, EventHandler<any>>;
  }

  interface DocumentFragment {
    blockId?: string;
    __handlers?: any;
  }
}

type EventHandler<T extends EventTarget = EventTarget> = (
  e: SyntheticEvent<T>,
) => void;

type SyntheticEventHandler<
  T extends HTMLElement,
  K extends keyof HTMLElementEventMap,
> = (e: SyntheticEvent<T>) => void;

type DOMEventProps<T extends HTMLElement> = {
  [K in keyof HTMLElementEventMap as `on${K}`]?: SyntheticEventHandler<T, K>;
};

/*
  type Attrs<T extends keyof HTMLElementTagNameMap> = Partial<
  HTMLElementTagNameMap[T]
> &
  Partial<Omit<HTMLElementTagNameMap[T], keyof HTMLElement>> &
  DOMEventProps<HTMLElementTagNameMap[T]> & {
    class?: string
    ref?: string;
    children?: HTMLElement | HTMLElement[];
  };
*/

// type ElementRef<
//   T extends keyof HTMLElementTagNameMap = keyof HTMLElementTagNameMap,
// > = {
//   el: HTMLElementTagNameMap[T] | null;
//   _tag: T | string;
// };

type ElementRef<T> = {
  el: T | null;
  _tag: string | undefined;
};

type Attrs<T extends keyof HTMLElementTagNameMap> = Partial<
  Omit<HTMLElementTagNameMap[T], keyof HTMLElement>
> &
  DOMEventProps<HTMLElementTagNameMap[T]> & {
    /** CSS classes to apply to the element */
    class?: string;
    /** Unique ref generated by useElementRef to select this element later. */
    ref?: ElementRef<HTMLElementTagNameMap[T]>;
    children?: HTMLElement | HTMLElement[];
    style?: CSSStyleDeclaration;
  };

type TagName = keyof HTMLElementTagNameMap;
type RectorElements = {
  [K in TagName]: (attributes: Attrs<K>) => HTMLElementTagNameMap[K];
};

namespace RectorJSX {
  export type Element = HTMLElement | ChildNode | DocumentFragment;
  export type DOM = {
    [K in TagName]: (attributes: Attrs<K>) => HTMLElementTagNameMap[K];
  };
}

type StateUsage = {
  [state: string]: StateUseObj[];
};

type AttrsUsage = {
  [state: string]: AttrUseObj[];
};

type StateLoopBlocks = {
  [stateName: string]: string[];
};

type StateIfBlocks = {
  [scope: string]: {
    [stateName: string]: string[];
  };
};

type RectorElementRef<T extends keyof HTMLElementTagNameMap> = {
  [refName: string]: HTMLElementTagNameMap[T];
};
// interface IfBlockConfig {
//   rawExp: RawJSXExpression;
//   trueElement?: () => HTMLElement | ChildNode;
//   falseElement?: () => HTMLElement | ChildNode;
//   placeholder?: Range;
//   cmpId?: string;
//   childBlock?: string;
// }

type StateUseObj = {
  element: HTMLElement;
  pos: number;
  eval: () => any;
  cmpId: string;
};

type AttrUseObj = {
  element: HTMLElement;
  eval: () => any;
  attribute: string;
  cmpId: string;
};

type IfBlockConfig = {
  elementRange: Range;
  cmpId: string;
  prevVal: boolean;
  childBlock: string;
} & JSXConditionObj;

interface LoopBlockConfig {
  renderElement?: (item: any, index: number) => HTMLElement;
  startRef: Comment;
  endRef: Comment;
  keyExtractor?: (item: any, index: number) => string | number;
  cmpId?: string;
  childBlocks?: Set<string>;
  data?: JSXExpressionObj;
}

type StateUsageConfig =
  | {
      type: "condition";
      config: IfBlockConfig;
    }
  | {
      type: "loop";
      config: LoopBlockConfig;
    }
  | {
      type: "child";
      config: StateUseObj;
    }
  | {
      type: "attr";
      config: AttrUseObj;
    };

type Block = {
  componentRendered: string[];
  stateUsageCleanUps: (() => void)[];
  stateUsageRefIds: number[];
};

type State<T> = {
  readonly value: T;
  set(val: T | ((prev: T) => T)): void;
};

type List<T> = {
  readonly value: readonly T[];
  readonly length: number;
  set(val: T[] | ((prev: readonly T[]) => T[])): void;
  update(index: number, value: T): void;
  insert(index: number, ...values: T[]): void;
  push(...values: T[]): void;
  unshift(...values: T[]): void;
  pop(): void;
  shift(): void;
  remove(index: number): void;
  removeRange(start: number, end: number): void;
};

type BatchTypes = "insert" | "update" | "remove" | "removeRange";

type RenderBatch =
  | {
      type: "set";
      index?: number;
      value?: any;
      state: State<any> | List<any>;
    }
  | {
      type: BatchTypes;
      index?: number;
      value?: any;
      state: List<any>;
    };

interface EffectConfig {
  [id: string]: {
    depends: State<any>[];
    scope: string;
    fn: () => void | Promise<void> | (() => void);
    cleanUp?: () => void;
    phase?: "l";
  };
}

type EffectOptions = {
  runOnMount: boolean;
  phase: "layout" | "effect";
};

type ElementInterceptors = {
  [Tag in keyof HTMLElementTagNameMap]?: (
    el: HTMLElementTagNameMap[Tag],
  ) => void;
};

// type Rector.JSX.Element = () => HTMLElement | ChildNode;

type RouteKeyPair = {
  [path: string]: RouteConfig;
};

type MetaConfig = {
  meta?: { description?: string };
  documentTitle?: string;
};

type MiddlewareContext = {
  path: string; // current path
  redirect(to: string): void;
  abort(fallbackUrl?: string): void;
};

type NavigationAction =
  | { type: "goAhead" }
  | { type: "abort"; fallbackUrl?: string }
  | { type: "redirect"; to: string };

type RouteConfig = {
  layout?: (child: () => RectorJSX.Element) => HTMLElement;
  children?: RouteKeyPair;
  component?: () => RectorJSX.Element;
  config?: MetaConfig;
  middleware?: (context: MiddlewareContext) => void | Promise<void>;
  loading?: () => RectorJSX.Element;
};

type Route = {
  lid?: number | number[];
  component: () => RectorJSX.Element;
  config?: MetaConfig;
  middleware?: (context: MiddlewareContext) => void | Promise<void>;
  loading?: () => RectorJSX.Element;
};
interface JSXExpressionObj {
  eval: () => any;
  states: State<any>[];
}

interface JSXConditionObj {
  eval: () => boolean;
  states: State<any>[];
  then: () => HTMLElement | ChildNode | DocumentFragment;
  else: () => HTMLElement | ChildNode | DocumentFragment;
}

const LIST_MARKER = Symbol("RECTOR_LIST");

type LIST<T> = { readonly [LIST_MARKER]: true; readonly value: T[] };

type GlobalStates<T> = {
  [K in keyof T]: T[K] extends LIST<infer U>
    ? List<U> // If it is already a List, return List Type
    : State<T[K]>; // If it is a primitive (number/string), wrap in State Type
};
// type RectorRefs = {
//   [K in keyof HTMLElementTagNameMap]: {
//     [refName: string]: HTMLElementTagNameMap[K];
//   };
// };

export {
  LIST,
  LIST_MARKER,
  GlobalStates,
  Attrs,
  EffectConfig,
  RectorElements,
  StateIfBlocks,
  StateLoopBlocks,
  StateUseObj,
  RectorElementRef,
  IfBlockConfig,
  LoopBlockConfig,
  ElementInterceptors,
  Route,
  RouteKeyPair,
  RouteConfig,
  JSXExpressionObj,
  JSXConditionObj,
  MetaConfig,
  RectorJSX,
  AttrsUsage,
  State,
  List,
  RenderBatch,
  StateUsageConfig,
  Block,
  NavigationAction,
  EffectOptions,
  ElementRef,
};

// in future

// interface GlobalAttributes {
//   id?: string;
//   class?: string;
//   style?: string;
//   title?: string;
//   hidden?: boolean;
//   children?: HTMLElement | HTMLElement[];
//   [key: string]: any; // allow data-*, aria-*
// }

// interface ElementAttributesMap {
//   div: GlobalAttributes & {
//     // no innerHTML, innerText
//   };
//   input: GlobalAttributes & {
//     type?: string;
//     name?: string;
//     value?: string;
//     placeholder?: string;
//     disabled?: boolean;
//   };
//   // Add more as needed
// }

// type Attrs<T extends keyof ElementAttributesMap> = ElementAttributesMap[T];
